name: Build app

on:
  push:
    branches:
      - "dev"
      - "main"
    paths:
      - "WatchIt**"
  pull_request:
    branches:
      - "dev"
      - "main"
    paths:
      - "WatchIt**"

jobs:
  build_and_test:
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore